feat: 이름 입력 화면 구현
softeerbootcamp-3nd/softee5-15zizo-FE pull request #18
Opened 2024-01-06 14:06 UTC by chjih

## 개요

- #10 

##  작업사항

- 이름 입력 화면 구현
- 이름 입력 시 시작 / 수정 화면 구현
- img파일 임의로 docs파일 밑에 만듬 (추후 수정?)

<img width="30%" alt="스크린샷 2024-01-06 오후 10 48 13" src="https://github.com/softeerbootcamp-3nd/softee5-15zizo-FE/assets/81521128/00c4d3d4-284b-41b6-a1f1-97aa92d313df"><img width="30%" alt="스크린샷 2024-01-06 오후 10 48 28" src="https://github.com/softeerbootcamp-3nd/softee5-15zizo-FE/assets/81521128/1be58f8b-5141-4679-be43-20a5dae57eed"><img width="30%" alt="스크린샷 2024-01-06 오후 10 49 00" src="https://github.com/softeerbootcamp-3nd/softee5-15zizo-FE/assets/81521128/3c960fa3-3a37-455c-9ba9-b0ec23e4a438">

2024-01-06 15:02 UTC, junhea approved these changes

2024-01-06 15:02 UTC, junhea commented on docs/js/pages/register/stages/Name.js
> +                this.setState({modal:true});
머지할때 props.proceed 함수 사용해서 name 값을 register의 state에 넣어주세요

2024-01-06 15:11 UTC, junhea requested changes

2024-01-06 15:11 UTC, junhea commented on docs/js/pages/register/stages/Name.js
> +                console.log("start");
props.proceed 함수 사용해서 name 값을 register의 state에 넣어주세요
```js
props.proceed({name: this.state.name});
```

2024-01-06 15:12 UTC, junhea approved these changes

2024-01-06 15:43 UTC, junhea requested changes

2024-01-06 15:43 UTC, junhea commented on docs/js/pages/register/stages/Name.js
> +            this.state.name = e.target.value;
state를 직접 설정하지 말고 setState를 사용해 주세요
```js
this.setState({name:e.target.value})
```

2024-01-07 00:08 UTC, junhea approved these changes

2024-01-07 02:33 UTC, chjih commented
Close #10

2024-01-07 02:37 UTC, merged